

/* Create Tables */

CREATE TABLE PRODUCT
(
	ID INT NOT NULL UNIQUE AUTO_INCREMENT COMMENT 'ID',
	TITLE VARCHAR(100) NOT NULL UNIQUE COMMENT 'タイトル',
	PLAY_DATE DATE NOT NULL COMMENT '公開日',
	COUNTRY_OF_PRODUCTION VARCHAR(100) NOT NULL COMMENT '製作国',
	RUNNING_TIME INT NOT NULL COMMENT '上映時間',
	PRIMARY KEY (ID)
) COMMENT = 'NEW_TABLE';



